apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: alpine/helm
      command:
        - cat
      tty: true
      volumeMounts:
        - name: jenkins-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: jenkins-token
      secret:
        secretName: jenkins
