---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: tomcatsample
        image: tomcatsample